version: '3'
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    build: .
    container_name: server
    env_file: ./.env
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - './:/src'
    command: npm run start:container
volumes:
  postgres:
    driver: local
  pgadmin-data:
    driver: local
